### ISSUE TITLE
Can't be used with STL model

### ISSUE THREAD

**Issue by below-1** [gkjohnson/three-bvh-csg#83]
STL model doesn't have UV mapping. When apply CSG operation to loaded STL object, It will throw an error.

**Comment by gkjohnson** [comment]
Hello! What error is thrown? It's important for each of the brushes to have the same vertex attributes but perhaps that can be communicated more effectively in the docs and errors.

**Comment by below-1** [comment]
Sorry just answering now. After reading the source, it appears UV attributes must exists in operated geometry. So I decided to generate UV for my STL model.

**Comment by brucedjones** [comment]
Hm looks like uv's are assumed. I had an issue where one model has a `uv` attribute and another doesn't. I called `deleteAttribute('uv')` on the model that has is, but then ran in to an error because the evaluator does assume there is a `uv` attribute:

https://github.com/gkjohnson/three-bvh-csg/blob/7ec1b6f839bfb0eb95d43cadbf6d56f1eacee4f6/src/core/Evaluator.js#L129

**Comment by brucedjones** [comment]
I confirmed locally that simply removing the `uv` property there allows everything to work
