### ISSUE TITLE
Correct way to combine multiple meshes?

### ISSUE THREAD

**Issue by John-Dean** [gkjohnson/three-bvh-csg#86]
Hi there,

I'm looking to use the ADDITION operation with multiple meshes. I see in your example: https://gkjohnson.github.io/three-bvh-csg/examples/bundle/simple.html this has the output I expect.

The example combines 2 meshes; a sphere and a cube.

What would be the correct process for combining say 5 meshes (let's name them A B C D E)?

Is there a way of combining all 5 in 1 in a single command?
Or do you have to do (((A+B) + C) + D) + E?
Or is ( (A+B) + (C+D) ) + E more efficient? 

I'm just trying to understand the best way to approach this problem when the number of meshes grows to a few thousand.

Many thanks,
John

**Comment by gkjohnson** [comment]
Hello! Performance is still in progress and there are still some implementation quirks affecting speed but that aside I have not benchmarked or done any notional computation complexity comparisons for the types of operational hierarchy differences your asking. My gut says there's value to keeping the operations hierarchy shallow rather than deep but I can't be sure.

If you'd like to contribute a benchmark (see [benchmark folder](https://github.com/gkjohnson/three-bvh-csg/tree/main/benchmark)) or some kind of computational breakdown to figure this out and contribute it back it would be good to have!
